= migae modules

Implementing
link:https://cloud.google.com/appengine/docs/java/modules/[Google
AppEngine modules] in Clojure.

== checklist

Module versions may specified in:

* module's build.gradle, version='x.y.z'
* module's webapp/WEB-INF/appengine-web.xml
** <application> and <version> are ignored?
** <module> must match value specified in ear's application.xml?
* ear module's src/main/application/META-INF/application.xml, as <web-uri> (also maven-application.xml)

== notes

these notes apply to the gradle system

The name of the module's wardir in exploded app seems to be taken from
the name of the module's root directory in the source tree!  in other
words the build is not controlled by appengine-web.xml but by source
layout and build.gradle.

if you do not put a version prop in build.gradle for your module, then
the constructed wardir in exploded-app will be just the directory name
- not the module name specified in appengine-web.xml!

the module name specified in appengine-web.xml controls which projects
are modules, and which is the default module.  every module except the
default one must have a <module> entry in appengine-web.xml, no
duplicates.  controls name of module instances.

by contrast, the module definitions in ear's application.xml just
indicate which directories in exploded-app are to be treated as
modules.

in other words, the mapping goes like this: module name (specified in
appengine-web.xml) runs at a host:port (startup msg: "INFO: Module
instance x is running at http://localhost:53922/"), which is mapped to
a wardir (specified in application.xml) in exploded-app.

port can be specified in ear's build.gradle:

appengine {
    daemon = false
    httpAddress = '0.0.0.0'  // to test android
    httpPort = 8080  // port for default module; for others, use jvmFlags:
    jvmFlags = [
	'-Dcom.google.appengine.devappserver_module.memcache-0.1.0.port=8081',
	...etc...
    ]
}

you can name your <module> anything in appengine-web.xml, but if you
want to specify a port for it during development, make it match the
project dirname with suffixed version, so it will match the generated
wardir.

Summary: the (unversioned) module name is the dirname of the
subproject root; the version is set in build.gradle; the versioned
module name (unversioned name, hyphen, version) is used to generate
the wardir in exploded-app/; therefore:

* set <module> in application-web.xml to the versioned name
* do the same for <web-uri> in application.xml

this means you have to specify the version in three places, but that's life.

In ear's application.xml, <web-uri> for module does not create the directory, just controls where the container will look.  What controls creation of the dir (in exploded-app) is the appengine-web.xml for the module, <module> element.

moral of the story:  make sure <module> (in appengine-web.xml) matches <web-uri> (in application.xml in ear module)